swagger: "2.0"
info:
  title: image-api
  version: 1.0.0
paths:
  /v1/images/upload:
    post:
      operationId: upload
      x-google-backend:
        address: https://REGION-PROJECT.cloudfunctions.net/upload-image
      security:
        - api_key: []
      responses:
        "202":
          description: Accepted
securityDefinitions:
  api_key:
    type: apiKey
    name: key
    in: query

